### ISSUE TITLE
建议制作一个docker版

### ISSUE THREAD

**Issue by wdnmd32** [foamzou/melody#1]
感谢大佬优秀的项目，个人认为docker版更方便部署和管理

**Comment by rfrftt** [comment]
Dockerfile可以暂时自己编译下
---
FROM node:17.9.0-buster
RUN apt update && apt install -y ffmpeg git vim && ffmpeg -version
RUN git clone 'https://github.com/foamzou/melody.git' /melody && cd /melody && node init.js
EXPOSE 5566
CMD exec node /melody/backend/src/index.js
---

**Comment by foamzou** [comment]
会尽快安排下。

**Comment by dysf888** [comment]
> 会尽快安排下。

同求 目前已在 本机Windows搭建,希望出docker版后 可以支持数据迁移, 计划跑在openwrt上

**Comment by foamzou** [comment]
@wdnmd32 @rfrftt @dysf888 
已支持。见 README
