### ISSUE TITLE
[Feature Request] 不使用CDN加载js/css库，改为本地加载

### ISSUE THREAD

**Issue by ttttmr** [foamzou/melody#104]
**功能描述**

将cdn加载的静态资源改为本地加载

**为什么需要该功能**

正在使用的staticfile.org和bootcdn.net域名，有潜在投毒可能，参考[供应链投毒后，我们的选择还剩下哪些？](https://v2ex.com/t/1056428)

另外本地加载也会快一些

**Comment by foamzou** [comment]
1. 我解释下为什么要用 CDN

优化页面打开的体验。我的初衷是将其部署在云服务器，而云服务的带宽一般都挺低（例如我的机子只有 1M 带宽，理论上行 128KB/s）。第三方的那些库加起来有 800+KB，首次加载白屏时间将会很长（可能可以拆包 & 按需请求优化，但当时想 CDN 可以解决这个问题，所以没有做这个调研）。

2. 担心 CDN 投毒？

即使不投毒，第三方仍然没有本地安全和可靠。加上这几天遇到 AD Block 插件不知道为什么 block 了以上 CDN（没有细看是其中一个还是 both），确实 CDN 有其不可靠之处。

Action:

1. 请求帮助：有精力的小伙伴可以帮忙优化下这个问题：本地存储 + 拆包 + 按需请求
2. 我自己做（按目前时间精力来说，优先级会很低）

**Comment by ttttmr** [comment]
看了下uBlock Origin把两个域名都被block了 https://github.com/uBlockOrigin/uAssets/pull/24285

**Comment by foamzou** [comment]
@ttttmr Merged. Thanks for you effort

**Comment by foamzou** [comment]
Has been updated the docker.
