### ISSUE TITLE
成功安装，但是检测是否更新成功时出问题

### ISSUE THREAD

**Issue by Generous-CH** [foamzou/melody#108]
nodejs 和ffmpeg的环境都配好了，使用管理员权限安装时出现下面问题
C:\Users\ch\melody>npm run init
> foamzou-melody@0.1.2 init
> node scripts/setup.js
开始执行...
安装 node_module via npm
npm
 WARN config production Use `--omit=dev` instead.
up to date in 388ms
23 packages are looking for funding
  run `npm fund` for details
检查 media-get
start to get latest version from: https://mirror.ghproxy.com/https://raw.githubusercontent.com/foamzou/media-get/main/LATEST_VERSION
latest version: 0.2.13
当前 media-get 版本已经是最新版本
检查 media-get 是否更新成功
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/foamzou/howler.js.git
npm ERR! ssh: connect to host github.com port 22: Connection refused
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm
 ERR!     D:\codesoftware\nodejs\node_cache\_logs\2024-08-14T08_57_01_717Z-debug-0.log

安装前端 node_module 失败

**Comment by Generous-CH** [comment]
在网上搜了一下，貌似是因为用的是ssh的问题，但是我去看了package.json文件的url的，是http，很奇怪

**Comment by foamzou** [comment]
可能是你的网络和 github 不通的缘故。如果无法解决网络问题，可以把那个依赖先去掉，影响的只是移动端网页不能播放歌曲

**Comment by Generous-CH** [comment]
> 可能是你的网络和 github 不通的缘故。如果无法解决网络问题，可以把那个依赖先去掉，影响的只是移动端网页不能播放歌曲

谢谢大佬，成功了
