### ISSUE TITLE
Melody后续功能

### ISSUE THREAD

**Issue by dysf888** [foamzou/melody#11]
Melody，你的音乐精灵，旨在帮助你更好地管理音乐。目前的主要能力是帮助你**将喜欢的歌曲或者音频上传到音乐平台的云盘**。

刚刚出了Docker版,完美跑在openwrt,我觉得Melody完全可以更强大,直接作为本地私人播放器,解锁的音乐可以存在本地.不知道后续发展是否会走向这个功能.

**Comment by foamzou** [comment]
暂时没有做成播放器的计划。本地播放器，我最近看到 yes player 似乎还不错，可以看看。
