### ISSUE TITLE
希望能制作 arm64 的 Docker 镜像

### ISSUE THREAD

**Issue by Remawater** [foamzou/melody#12]

**Comment by foamzou** [comment]
跑在 m1 上边吗？

**Comment by foamzou** [comment]
@Remawater 你好，可以帮忙测试下吗？刚给所有平台重新 build 了一遍。还是使用 README 那个命令

**Comment by Remawater** [comment]
> @Remawater 你好，可以帮忙测试下吗？刚给所有平台重新 build 了一遍。还是使用 README 那个命令

好的 稍等

**Comment by Remawater** [comment]
`
docker pull foamzou/melody:latest
docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
`
出现了2个奇怪的容器
`
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS                     PORTS     NAMES
a6cf486d68ec   foamzou/melody:latest   "node backend/src/in…"   3 minutes ago   Exited (1) 3 minutes ago             quizzical_moser
be31ee30c375   foamzou/melody:latest   "node backend/src/in…"   5 minutes ago   Exited (1) 5 minutes ago             brave_wu
`
日志都是  stderr: standard_init_linux.go:228: exec user process caused: exec format error

**Comment by foamzou** [comment]
可以检查下本地拉下来的镜像是否为 arm 的
```
docker image inspect foamzou/melody:latest | grep Architecture
```

**Comment by Remawater** [comment]
> 可以检查下本地拉下来的镜像是否为 arm 的
> 
> ```
> docker image inspect foamzou/melody:latest | grep Architecture
> ```
"Architecture": "arm64"
是Arm的 还是一样容器启动后：stderr: standard_init_linux.go:228: exec user process caused: exec format error

**Comment by foamzou** [comment]
原因是 docker 里基础镜像和我的media-get 之前不支持 arm64。
我重新调整和编译，并弄了个 arm64 centos 服务器测试通过了。
可以帮忙 docker pull 再 run 试试
@Remawater

**Comment by Remawater** [comment]
🎇🎉🎉🎉 一切正常

**Comment by foamzou** [comment]
好的，谢谢反馈
