### ISSUE TITLE
独立部署时无法通过验证

### ISSUE THREAD

**Issue by CelestialCosmic** [foamzou/melody#14]
我试图将其集成到内网的 nginx ，但是编译出来后，无法验证，没有搞明白 account 要的是什么。试过将`.profile`里面的东西拿出来用，也没有用。
![2022-05-10_21-00](https://user-images.githubusercontent.com/89504915/167634258-ac998b52-1247-458c-b955-9035af424e87.png)

**Comment by foamzou** [comment]
404 了，请求没有抵达服务。
请确保你的 18443 端口指向的是 melody 的服务

**Comment by CelestialCosmic** [comment]
> 404 了，请求没有抵达服务。 请确保你的 18443 端口指向的是 melody 的服务


页面是可以正常访问的，但是输入 melody key 的时候显示找不到存放账户的文件，因此无法通过验证
我认为手动干预 `/api/account` 即可，但是我不明白这里需要什么文件，因为 `run app` 时产生了 `.profile` ，而 `.profile` 在我尝试的时候并不能用，

**Comment by foamzou** [comment]
如果有环境部署重现步骤的话，我可以尝试一下。

**Comment by CelestialCosmic** [comment]
> 如果有环境部署重现步骤的话，我可以尝试一下。

服务器的配置
```
server {
    listen      18443;
    server_name melody;
    set $base /home/admin/melody/backend/public;
    root        $base;
    }
```

编译（yarn run init）后使用默认帐号（melody）登入

未修改源代码
