### ISSUE TITLE
播放中和新搜索的歌曲共用状态了

### ISSUE THREAD

**Issue by ottocsb** [foamzou/melody#22]
![image](https://user-images.githubusercontent.com/83228451/168717242-3fcc9b04-8bfd-40e0-9b69-9df9b80e20bb.png)
如图，正在播放‘不留’，新搜索的歌曲展示的list，第一位显示播放中

**Comment by ottocsb** [comment]
切换了一首名字长的歌曲，出现了排版问题
![image](https://user-images.githubusercontent.com/83228451/168717555-bfbde14f-acde-433b-8bce-85dcedd5f72f.png)

**Comment by foamzou** [comment]
是的 已知问题。会找时间优化下

**Comment by foamzou** [comment]
播放状态已 fix
