### ISSUE TITLE
无法上传解锁歌曲

### ISSUE THREAD

**Issue by JamesWDGu** [foamzou/melody#3]
ℹ fetchWithUrl params: {"0":"https://y.qq.com/n/ryqq/songDetail/004Z8Ihr0JIu5s","1":{"songName":"七里香","addMediaTag":false}}                                                                                               12:41:22
ℹ start parse and download from https://y.qq.com/n/ryqq/songDetail/004Z8Ihr0JIu5s                                                                                                                                            12:41:22

 ERROR  exec error: Error: Command failed: /Users/.../melody/backend/src/service/media_fetcher/../../../bin/media-get -u "https://y.qq.com/n/ryqq/songDetail/004Z8Ihr0JIu5s" --out "/var/folders/5r/ct4_6f8j3zv8sx303l0jlvrc0000gn/T/melody-tmp-songs/d7070ce48106b02b1f4a700cdf000431/七里香.mp3" -t audio
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/foamzou/audio-get/utils.GetExtFromUrl(0x0, 0x0, 0x9, 0x144efbd)
	github.com/foamzou/audio-get/utils/url.go:11 +0x175
github.com/foamzou/audio-get/processor.(*Processor).downloadAudio(0xc0001a1f68, 0xc0001fa000, 0xc0228dd2f1a9fbe7, 0x401d353f7ced9168)
	github.com/foamzou/audio-get/processor/download.go:36 +0x55a

**Comment by foamzou** [comment]
周杰伦的歌曲，qq 音乐没有公共资源的。
搜索结果中，qq 音乐的权重应该很低才对，咪咕应该排在第一位(可以使用咪咕)。
这类可能无法播放和上传的歌曲，搜索列表的那行最前面会有个 锁 的标识。
后面看看怎么优化下交互体验。

**Comment by JamesWDGu** [comment]
> 周杰伦的歌曲，qq 音乐没有公共资源的。 搜索结果中，qq 音乐的权重应该很低才对，咪咕应该排在第一位(可以使用咪咕)。 这类可能无法播放和上传的歌曲，搜索列表的那行最前面会有个 锁 的标识。 后面看看怎么优化下交互体验。

明白了，谢谢回复
