### ISSUE TITLE
添加自动构建Docker的支持

### ISSUE THREAD

**Issue by eryajf** [foamzou/melody#30]
看了下项目的dockerfile，感觉非常适合借助 GitHub Actions 的能力，自动构建docker镜像，而且还能自动构建多架构平台支持的镜像，这样会省心非常多。

这个是我一个前端项目的配置文件： https://github.com/eryajf/go-ldap-admin-ui/blob/main/.github/workflows/docker-image.yml

可以简单更改就能投入使用，当然，如果需要我补充这个PR，我也非常乐意效劳！

**Comment by foamzou** [comment]
谢谢贴心的建议，github action 在计划内，不过因为构建中有一些边缘 case 导致构建失败，需要人工处理。所以还未添加这项配置。
处理好构建健壮性，测试可用性以及版本发布策略后会添加。
