### ISSUE TITLE
几乎没有能上传的

### ISSUE THREAD

**Issue by ChuGary** [foamzou/melody#37]
i fetchWithUrl params: {"0":"https://music.163.com/#/song?id=209043","1":{"songName":"优先权","addMediaTag":false}}
i start parse and download from https://music.163.com/#/song?id=209043
i C:\Users\garyc\Documents\Tools\Melody\melody\backend\src\service\media_fetcher/../../../bin/media-get.exe -u "https://music.163.com/#/song?id=209043" --out "C:\Users\garyc\AppData\Local\Temp\melody-tmp-songs/7556ca6b9b3772f877305218d7d90d10/优先权.mp3" -t audio
C:\Users\garyc\Documents\Tools\Melody\melody\backend\src\service\media_fetcher/../../../bin/media-get.exe [
  '-u',
  '"https://music.163.com/#/song?id=209043"',
  '--out',
  '"C:\\Users\\garyc\\AppData\\Local\\Temp\\melody-tmp-songs/7556ca6b9b3772f877305218d7d90d10/优先权.mp3"',
  '-t',
  'audio',
  ''
]
i -------
i 0
**i invalid argument for flag `/o, /out' (expected string): invalid syntax**

i -------

**Comment by foamzou** [comment]
Hi 朋友。 @ChuGary 
我刚翻出 windows 测试了下，的确在 win 有一个兼容性问题。下个版本修复。
你可以编辑 `/backend/src/service/media_fetcher/index.js` 文件,将
```
`"${downloadPath}"`
```
 中的双引号删除。即，修改为如下：
```
`${downloadPath}`
```
这样就可以成功下载了。

另外有一些建议： 
1. 我注意到你贴的日志里边，你尝试下载 `https://music.163.com/#/song?id=209043` ，这是一个付费歌曲，是无法下载的。你可以选择咪咕的资源进行上传（上传前可以先点击播放按钮试听一下）。（如下图）
2. 若你的歌已经收藏在歌单，那么在歌单 tab 里进行解锁是个更方便的选择
3. 条件允许的话，尽可能使用 docker 部署，能够在大程度上避免兼容性问题

![image](https://user-images.githubusercontent.com/9295077/184539840-27e0849e-1a2e-4223-9a7b-1aa4dbbc2a99.png)

**Comment by ChuGary** [comment]
谢谢，已解决~

**Comment by foamzou** [comment]
已修复
