### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by fanhua1550** [foamzou/melody#40]
开始执行...
检查 media-get
当前 media-get 版本已经是最新版本
检查 media-get 是否更新成功
安装 node_module
����: �Ҳ������޷��������� install

����: �Ҳ������޷��������� install

编译前端
����: �Ҳ������޷��������� run

删除老目录
拷贝前端目录
执行完毕，执行以下命令启动服务：

npm run app
(node:11068) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

> foamzou-melody@0.1.1 app
> node backend/src/index.js

D:\develop\other\melody\backend\src\service\media_fetcher/../../../bin/media-get.exe [ '-h' ]
i [media-get] Version: 0.2.6                                                                                  18:12:49
i [tmp path] use C:\Users\Jios\AppData\Local\Temp\melody-tmp-songs                                            18:12:49
i Express server is listening on :::5566!                                                                     18:12:50

安装到最后，浏览器输入http://127.0.0.1:5566/，页面就是这个提示Cannot GET /，F12出来这页面是404，这个怎么处理。

**Comment by foamzou** [comment]
暂未遇到过类似的错误。猜测：
1. 因为某些原因，`backend/public/index.html` 未生成。可以检查确认一下，如未生成，可以手动编译前端项目，将 dist 目录下的文件拷贝到 `backend/public/`
2. 启动的 node 程序没有权限读 `backend/public/` 目录下的文件。没有用户反馈过相关权限问题，但你可以确认一下。

**Comment by foamzou** [comment]
@fanhua1550 你好，后面解决了吗

**Comment by fanhua1550** [comment]
还没测试，npm编译这个我不会。我用2种安装方式都是这样，docker或者npm，FFmpeg 这个环境也配置过了，输入也有效果。但是我的FFmpeg 安装路径有空格，还没测试没空格的。

**Comment by foamzou** [comment]
从 docker hub 拉下来也有问题的话，我就无解了。因为 hub 上边的都是编译好的了。
```
docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
```

**Comment by fanhua1550** [comment]
> 从 docker hub 拉下来也有问题的话，我就无解了。因为 hub 上边的都是编译好的了。
> 
> ```
> docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
> ```

已经可以了，用你这条命令。
