### ISSUE TITLE
请问如何一键下载歌单？

### ISSUE THREAD

**Issue by sruby** [foamzou/melody#42]
请问如何一键下载歌单？

**Comment by sruby** [comment]
发现可以通过云盘下载。

**Comment by foamzou** [comment]
云盘可以一键下载歌单吗？ @sruby 
还是说你的需求背景，结合云盘可以实现 👀

**Comment by sruby** [comment]
> 

想批量下载歌单中的歌曲。
发现目前可以达到这个目的：
1. 一键解锁所有歌曲；
2. 使用网易云app到云盘批量下载；
