### ISSUE TITLE
不知道为什么key不正确

### ISSUE THREAD

**Issue by aaaol** [foamzou/melody#44]
![image](https://user-images.githubusercontent.com/28624574/186455810-f26e95bc-e167-4c21-8bc3-b9311b9c2d05.png)
![image](https://user-images.githubusercontent.com/28624574/186456092-ee35eaa2-196a-4555-ae42-11d25460c445.png)
![image](https://user-images.githubusercontent.com/28624574/186456144-bd8e55fc-5567-453b-9b87-fb8d2c4a833e.png)
改一次都重启过了

**Comment by foamzou** [comment]
可以附上以下信息，帮助排查
1. 后端日志
2. F12 前端网络请求报文
3. F12 console 信息

**Comment by aaaol** [comment]
![image](https://user-images.githubusercontent.com/28624574/186464993-f62e0dc3-6fe4-46a5-a214-13c5f1cd7b43.png)
![image](https://user-images.githubusercontent.com/28624574/186465191-c0d6978e-996d-4ff9-8e93-70b1e70f7066.png)
`ERROR  requestWyyApi failed:  {
  status: 502,
  body: {
    code: 502,
    msg: Error: connect ETIMEDOUT 45.254.48.2:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '45.254.48.2',
      port: 443,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}


 ERROR  fetch cookie from response failed, uid(melody) login failed false


 ERROR  uid(melody) get cookie failed


 ERROR  request failed. false


 ERROR  requestWyyApi failed:  {
  status: 502,
  body: {
    code: 502,
    msg: Error: connect ETIMEDOUT 101.71.154.243:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '101.71.154.243',
      port: 443,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}


 ERROR  fetch cookie from response failed, uid(melody) login failed false


 ERROR  uid(melody) get cookie failed


 ERROR  request failed. false

      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}
ℹ uid(melody)'s cookie not found from .profile
ℹ uid(melody) login with undefined  via phone
{
  status: 502,
  body: {
    code: 502,
    msg: Error: connect ETIMEDOUT 101.71.154.243:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -110,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '101.71.154.243',
      port: 443,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}
`

**Comment by foamzou** [comment]
看起来你服务器（后端）所在网络与网易服务器不可达。网络问题。。
```
ping 101.71.154.243
```

**Comment by aaaol** [comment]
把网络切换成host就能用了
bridge不知道为什么用不了
