### ISSUE TITLE
[Feature Request] 支持下载MP3到本地

### ISSUE THREAD

**Issue by Never-NG** [foamzou/melody#49]
**功能描述**
现在音乐只是下载到/tmp目录，上传到云盘后就自动删除了。建议支持一键将歌单中所有音乐，下载MP3到本地，用作本地存储。

**为什么需要该功能**
在版权越来越严格的前提下，很多APP都有自己格式的音乐格式，不再提供通用MP3格式文件，不方便离线听取。

**你能想到的解决方案**
既然内部已经有获取网易云歌单列表和下载MP3的逻辑，建议增加一个「一键下载MP3到本地」的功能，方便离线存储。

**Comment by foamzou** [comment]
same as #20
