### ISSUE TITLE
解锁和上传云盘失败

### ISSUE THREAD

**Issue by Jungle-Leesin** [foamzou/melody#5]
![errormessage](https://user-images.githubusercontent.com/62128074/166958124-4fa15ab0-ae9d-4166-87e9-d695e72224e4.png)
我在使用部分解锁和上传时，出现此类错误

**Comment by foamzou** [comment]
不支持 qq 音乐 vip 歌曲。可以试试别的源

**Comment by foamzou** [comment]
Duplicate of #3

**Comment by Jungle-Leesin** [comment]
非常感谢，默认上传的质量为mp3，这个可以通过改配置来调整嘛

**Comment by foamzou** [comment]
目前不支持，可以另外提一个 issue。考虑后续支持用户设置歌曲质量偏好

**Comment by Jungle-Leesin** [comment]
好的，谢谢
