### ISSUE TITLE
[BUG]酷我/QQ不能播放

### ISSUE THREAD

**Issue by XOAMOX** [foamzou/melody#53]
## 请至少提供以下信息，帮助排查问题
1. 后端日志
ℹ searchSong with {"0":{"keyword":"平凡之路"}}
ℹ cmdStr: /app/backend/src/service/media_fetcher/../../../bin/media-get -k "平凡之路" --searchType="song" -m --infoFormat=json -l silence
/app/backend/src/service/media_fetcher/../../../bin/media-get [
  '-k',
  '"平凡之路"',
  '--searchType="song"',
  '-m',
  '--infoFormat=json',
  '-l',
  'silence'
]
ℹ -------
ℹ 0
ℹ -------
ℹ getMetaWithUrl from https://www.kuwo.cn/play_detail/146783118
/app/backend/src/service/media_fetcher/../../../bin/media-get [
  '-u',
  '"https://www.kuwo.cn/play_detail/146783118"',
  '-m',
  '--infoFormat=json'
]
ℹ -------
ℹ 2
ℹ -------

 ERROR  getMetaWithUrl failed with https://www.kuwo.cn/play_detail/146783118, err: panic: invalid character 'æ' looking for beginning of value

goroutine 1 [running]:
main.main()
        ./main.go:24 +0xab

ℹ getMetaWithUrl from https://y.qq.com/n/ryqq/songDetail/000T1Ws32MWrUj
/app/backend/src/service/media_fetcher/../../../bin/media-get [
  '-u',
  '"https://y.qq.com/n/ryqq/songDetail/000T1Ws32MWrUj"',
  '-m',
  '--infoFormat=json'
]
ℹ -------
ℹ 2
ℹ -------

 ERROR  getMetaWithUrl failed with https://y.qq.com/n/ryqq/songDetail/000T1Ws32MWrUj, err: panic: can not get song url

goroutine 1 [running]:
main.main()
        ./main.go:24 +0xab

## 复现步骤
搜索，播放仅此

**Comment by foamzou** [comment]
could watch and follow issue #58
