### ISSUE TITLE
[BUG] 无法登录网易云音乐

### ISSUE THREAD

**Issue by YunofHD** [foamzou/melody#57]
## 请至少提供以下信息，帮助排查问题
1. 后端日志
 ERROR  requestWyyApi failed:  {
  status: 502,
  body: {
    code: 502,
    msg: Error: connect ECONNREFUSED 0.0.0.0:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '0.0.0.0',
      port: 443,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  },
  cookie: []
}

 ERROR  fetch cookie from response failed, uid(melody) login failed false

 ERROR  uid(melody) get cookie failed

 ERROR  request failed. false

尝试再构建容器时把主机的高位端口映射给443端口，还是报相同错。

**Comment by foamzou** [comment]
看样子似乎是你的 dns 把网易云域名解析为了本地地址。猜测路由器用了 unblock 网易云音乐的服务？

**Comment by YunofHD** [comment]
Hi，感谢回复。
应该没有启用unblock服务，但是前置确实有open clash，更上层还有AD guard home。确实有可能是这两者影响的。
