### ISSUE TITLE
[BUG]mac 安装ffmpeg后 软件仍提示未安装

### ISSUE THREAD

**Issue by mizhewei** [foamzou/melody#62]
## 请至少提供以下信息，帮助排查问题
<img width="573" alt="图片" src="https://user-images.githubusercontent.com/38462600/196956153-558dae16-1705-44e4-a31a-3f640bec9da8.png">
mac系统 homebrew安装的ffmpeg
## 复现步骤

**Comment by foamzou** [comment]
可能是 ffprobe 没有安装

**Comment by mizhewei** [comment]
安装了呀 我还卸载重装过了 还是不行
<img width="92" alt="图片" src="https://user-images.githubusercontent.com/38462600/197335772-9f58b0c6-16da-4e42-8b33-9185c4c87daa.png">

**Comment by foamzou** [comment]
在 melody/backend/bin 目录下执行  `./media-get -h` 看看输出什么？
代码会从输出文本是否包含 `FFmpeg,FFprobe: installed` 来判断是否安装成功。

P.S 自己折腾环境比较麻烦，可以用 docker 就省事了。 @mizhewei

**Comment by mizhewei** [comment]
./media-get -h
zsh: killed     ./media-get -h
放弃了 转战docker
