### ISSUE TITLE
[Feature Request]请求适配cpu架构为s390x

### ISSUE THREAD

**Issue by Sliccic** [foamzou/melody#65]
两种安装方式均尝试了，无法安装

**Comment by Sliccic** [comment]
root@melody:~# docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
Unable to find image 'foamzou/melody:latest' locally
latest: Pulling from foamzou/melody
docker: no matching manifest for linux/s390x in the manifest list entries.
See 'docker run --help'.
这是第一个方法

**Comment by foamzou** [comment]
抱歉，暂时没有支持 linux/s390x 的计划。
如果你对 node 熟悉的话，可以尝试源码安装。外部的依赖主要是 ffmpeg， 这个相信你可以解决。还有一个是 [media-get](https://github.com/foamzou/melody), 这个在 s390x 编译一下，拷贝到对应目录（ 拷贝为 app/backend/bin/media-get ）就行。

**Comment by Sliccic** [comment]
> 

好的非常感谢麻烦你了
