### ISSUE TITLE
端口冲突，换了映射端口后key无法识别登录[BUG]

### ISSUE THREAD

**Issue by Chenze60** [foamzou/melody#68]
## 请至少提供以下信息，帮助排查问题
1. 后端日志
2. F12 前端网络请求报文
3. F12 console 信息

**Comment by foamzou** [comment]
请留下以下信息：
- 何种方式部署：源码部署，docker 部署？
- 换了映射端口，具体是怎么换的。例如，将 web service 的端口 还是 docker expose 的端口换了？
- 启动命令贴一下

以及，需要补充提 BUG 的模板的 3 个信息。
