### ISSUE TITLE
32位长度的字符串是什么，melody错误。PVE-omv的docker安装melody

### ISSUE THREAD

**Issue by baluoqi** [foamzou/melody#69]
![image](https://user-images.githubusercontent.com/51146932/209425298-d13978a1-406f-4ccd-af69-eb06a404c27e.png)

**Comment by baluoqi** [comment]
![image](https://user-images.githubusercontent.com/51146932/209425351-4969b55c-a587-45fb-bac8-f80e26ae8e66.png)

**Comment by baluoqi** [comment]
docker pull docker.io/foamzou/melody:latest
docker kill <CONTAINER ID>
docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
用这个部署

**Comment by foamzou** [comment]
编辑
```
vi ~/melody-profile/accounts.json
```

**Comment by baluoqi** [comment]
谢谢，重新部署搞定
