### ISSUE TITLE
[BUG] 疑似CPU 被占满

### ISSUE THREAD

**Issue by dfmjndm** [foamzou/melody#70]
## 请至少提供以下信息，帮助排查问题
1. 后端日志
2. F12 前端网络请求报文
3. F12 console 信息

## 复现步骤

docker版本，解锁两首音乐直接机器死机，2g空闲内存，大为不解

**Comment by foamzou** [comment]
你好。目前没有其他用户反馈过类似的问题。

Melody 没有直接把操作系统搞挂的能力哈，顶多把自己的进程给搞 kill。
因为你这里的描述只写了 “机器死机”，我没有更多的信息来诊断。
请问你的机器、操作系统是什么，死机具体是什么表现，CPU，内存被 melody 耗尽了还是其他。如果是 linux 机器，可以用 dmesg 看看有没有线索。

**Comment by dfmjndm** [comment]
centos8，2h4g，应该是CPU占满了把ssh挤掉了

**Comment by foamzou** [comment]
无更多线索，无法复现
