### ISSUE TITLE
国外机器无法正常使用，希望增加代理

### ISSUE THREAD

**Issue by x2287711259** [foamzou/melody#74]
**功能描述**
希望能加个代理，目前部署在国外vps上无法正常搜索和播放，另外youtube能搜索到，但是播放按钮为什么是灰色的

** 为什么需要该功能 **
国外机器搭建无法正常使用

**你能想到的解决方案**
本人小白，不懂技术，希望能尽量简单易用

**Comment by foamzou** [comment]
#58 有规划。懒癌恢复之后安排
