### ISSUE TITLE
能否实现做成openwrt可以安装的ipk

### ISSUE THREAD

**Issue by x2287711259** [foamzou/melody#75]
**功能描述**
希望能够做成openwrt可以安装的ipk，适配各种路由器架构

** 为什么需要该功能 **
对于硬路由刷openwrt的用户来说更方便

**你能想到的解决方案**
本人小白，alist这个项目可以，感觉这个应该也可以

**Comment by foamzou** [comment]
melody 是依赖 node.js 运行的，不是编译后能够独自运行的二进制文件。所以应该不行。
