### ISSUE TITLE
[BUG]docker构建，歌曲无法上传至网盘

### ISSUE THREAD

**Issue by Eison9** [foamzou/melody#76]
日志:

ℹ songFromWyCloud: null
ℹ fetchWithUrl params: {"0":"[https://www.youtube.com/watch?v=gCKiA_P9kRw","1"](https://www.youtube.com/watch?v=gCKiA_P9kRw%22,%221%22);:{"songName":"周杰倫 稻香 歌詞","addMediaTag":true}}
ℹ start parse and download from https://www.youtube.com/watch?v=gCKiA_P9kRw
ℹ /app/backend/src/service/media_fetcher/../../../bin/media-get -u "[https://www.youtube.com/watch?v=gCKiA_P9kRw"](https://www.youtube.com/watch?v=gCKiA_P9kRw%22); --out /tmp/melody-tmp-songs/1edb2e7098c6bb1c4de9eba84801b277/周杰倫稻香歌詞.mp3 -t audio --addMediaTag
/app/backend/src/service/media_fetcher/../../../bin/media-get [
'-u',
'"[https://www.youtube.com/watch?v=gCKiA_P9kRw"'](https://www.youtube.com/watch?v=gCKiA_P9kRw%22%27);,
'--out',
'/tmp/melody-tmp-songs/1edb2e7098c6bb1c4de9eba84801b277/周杰倫稻香歌詞.mp3',
'-t',
'audio',
'--addMediaTag'
]
ℹ -------
ℹ 2
ℹ panic: Get "": unsupported protocol scheme ""
goroutine 1 [running]:
main.main()
./main.go:25 +0xab
ℹ -------
ℹ searchSong with {"0":{"keyword":"稻香"}}
ℹ cmdStr: /app/backend/src/service/media_fetcher/../../../bin/media-get -k "稻香" --searchType="song" -m --infoFormat=json -l silence
/app/backend/src/service/media_fetcher/../../../bin/media-get [
'-k',
'"稻香"',
'--searchType="song"',
'-m',
'--infoFormat=json',
'-l',
'silence'
]
ℹ -------
ℹ 0
ℹ -------
ℹ getMetaWithUrl from https://y.qq.com/n/ryqq/songDetail/003aAYrm3GE0Ac
/app/backend/src/service/media_fetcher/../../../bin/media-get [
'-u',
'"[https://y.qq.com/n/ryqq/songDetail/003aAYrm3GE0Ac"'](https://y.qq.com/n/ryqq/songDetail/003aAYrm3GE0Ac%22');,
'-m',
'--infoFormat=json'
]
ℹ -------
ℹ 2
ℹ -------
ERROR  getMetaWithUrl failed with https://y.qq.com/n/ryqq/songDetail/003aAYrm3GE0Ac, err: panic: can not get song url
goroutine 1 [running]:
main.main()
./main.go:25 +0xab
ℹ false
ERROR  fetch song info failed or it's a trial song. false
ℹ getMetaWithUrl from https://y.qq.com/n/ryqq/songDetail/003aAYrm3GE0Ac
/app/backend/src/service/media_fetcher/../../../bin/media-get [
'-u',

**Comment by foamzou** [comment]
这些源都没有可用的资源。周杰伦的歌，建议你用咪咕的源

**Comment by Eison9** [comment]
@. @是我的问题吗，我部署在国外的docker，默认搜索出来并没有咪咕的源，其他歌也是

**Comment by Eison9** [comment]
> 这些源都没有可用的资源。周杰伦的歌，建议你用咪咕的源

@. @是我的问题吗，我部署在国外的docker，默认搜索出来并没有咪咕的源，其他歌也是

**Comment by Eison9** [comment]
已解决，建议用docker配置，很好用，云docker的话别用railway这种IP在国外的，加载不出来音乐

**Comment by foamzou** [comment]
Cool. 最后是用的哪里的 docker 呢，还是本地 docker 直接部署的？ @Eison9

**Comment by Eison9** [comment]
> Cool. 最后是用的哪里的 docker 呢，还是本地 docker 直接部署的？ @Eison9

最后还是在本docker地部署了
