### ISSUE TITLE
[BUG]腾讯音乐孤勇者可以搜索，但是无法播放和上传到网易云

### ISSUE THREAD

**Issue by ttglad** [foamzou/melody#78]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/7711709/236592018-8c304748-1de1-41b3-99d8-25c2690a00b6.png">

后端docker日志：
ℹ getMetaWithUrl from https://y.qq.com/n/ryqq/songDetail/003UkWuI0E8U0l
/app/backend/src/service/media_fetcher/../../../bin/media-get [
  '-u',
  '"https://y.qq.com/n/ryqq/songDetail/003UkWuI0E8U0l"',
  '-m',
  '--infoFormat=json'
]
ℹ -------
ℹ 2
ℹ -------

 ERROR  getMetaWithUrl failed with https://y.qq.com/n/ryqq/songDetail/003UkWuI0E8U0l, err: panic: can not get song url

goroutine 1 [running]:
main.main()
	./main.go:24 +0xab

 ERROR  fetch song info failed or it's a trial song. false

ℹ false

**Comment by foamzou** [comment]
我这边显示是🔐 的。 QQ 音乐大多不可用
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/9295077/236599906-cdf3a4ec-c676-4df7-a1cb-43aa95c98bc3.png">

**Comment by ttglad** [comment]
也换了好几个音乐合平台都不可以试听和上传

**Comment by foamzou** [comment]
你的 docker 是部署在国外吗？国外的话要挂国内代理哦（melody 的代理还在 TBC，后面支持）。所以你可以本地部署哦

**Comment by ttglad** [comment]
好的，了解了，我试试本地
