### ISSUE TITLE
[BUG]咪咕能搜索无法播放

### ISSUE THREAD

**Issue by x2287711259** [foamzou/melody#82]
咪咕目前能搜索，但是无法正常播放，之前是可以的。另外为什么youtube播放按钮是灰色的，好像一直都不能播放

**Comment by foamzou** [comment]
应该是咪咕改了机制。我有空看看。你有时间的话可以帮忙在 [github.com/foamzou./media-get](https://github.com/foamzou/media-get) 提个 PR？

**Comment by foamzou** [comment]
Duplicate #84

**Comment by foamzou** [comment]
Will check https://github.com/zonemeen/musicn/commit/8de872fde3ceb90886c2a664de9db3ec2456af86 or see if other solution

**Comment by foamzou** [comment]
类似问题 https://github.com/foamzou/melody/issues/94
