### ISSUE TITLE
[Feature Request]是否考虑集成musictag功能自动刮削

### ISSUE THREAD

**Issue by likeman66** [foamzou/melody#88]
**功能描述**
尽可能简单扼要地描述清楚需求
感谢大佬付出。就是想请问下后期是否有可能集成musictag的音乐刮削服务集成，因为我主要是下载到本地nas，然后link到emby，但是emby自带的音乐刮削比较鸡肋

** 为什么需要该功能 **
尽可能介绍清楚上下文，在什么场景下需要该功能

**你能想到的解决方案**
为实现该功能，你有什么建议吗

**Comment by foamzou** [comment]
music tag 集成到本服务后，期望的使用方式是什么呢？可以分享一下吗

**Comment by likeman66** [comment]
> music tag 集成到本服务后，期望的使用方式是什么呢？可以分享一下吗

抱歉，没注意到消息，就是下载到nas后，可以自动刮削一些基本信息，例如图片里这些信息：
![image](https://github.com/foamzou/melody/assets/59259075/89213123-e8ca-4f0c-ab16-87ac6003b615)
然后emby会自动识别信息滴～

**Comment by foamzou** [comment]
明白，谢谢你的建议。目前该 repo 不会有这方面的规划。

**Comment by sykeswzq** [comment]
> **功能描述** 尽可能简单扼要地描述清楚需求 感谢大佬付出。就是想请问下后期是否有可能集成musictag的音乐刮削服务集成，因为我主要是下载到本地nas，然后link到emby，但是emby自带的音乐刮削比较鸡肋
> 
> ** 为什么需要该功能 ** 尽可能介绍清楚上下文，在什么场景下需要该功能
> 
> **你能想到的解决方案** 为实现该功能，你有什么建议吗

怎么下载到NAS啊，我看只能下到网易云盘啊
