### ISSUE TITLE
[BUG]所有歌曲播放和上传失败

### ISSUE THREAD

**Issue by shugo-chara** [foamzou/melody#89]
发现了宝贝赶紧试了下。
win本地git后可以运行和登录，但所有歌曲搜索全部失败，上传失败。
换到nas的docker重新部署了下可以正常搜索了但是播放全部失败。
是海外用不了吗。
搜到的qq和kuwo的都无法播放。
看日志qq获取的链接正常，点进去可以听30秒，kuwo好像获取不到歌曲id。
youtube的播放按钮是灰色无法点击，我这边可以访问油管。

PS.请问可以选择自己本地的歌曲然后进行匹配并上传到网易云盘吗。如果无法从其他源下载的话，能自行准备音源然后通过这个服务器匹配到同样的歌曲并上传到云盘就好了。

![image](https://github.com/foamzou/melody/assets/20610965/259c204e-0952-4707-b411-d56118d9f22f)
![image](https://github.com/foamzou/melody/assets/20610965/b40a06e9-7bbb-4a9a-91fb-e3f1be9aa9ea)
![image](https://github.com/foamzou/melody/assets/20610965/020c07f5-a34d-470c-94d3-9f9d0ff06fda)

**Comment by foamzou** [comment]
@shugo-chara 你好，目前该项目不支持本地上传。
你可以在 github 找下类似的项目，例如（https://github.com/lulu-ls/cloud-uploader）。
匹配的话，网易云 安卓 app 是支持的。

我目前在修正咪咕的歌源，不过每周用在这个 repo 的时间很少，估计没那么快 fix。

**Comment by foamzou** [comment]
1. 海外网络的确无法使用本项目，因为国内很多音乐平台是屏蔽海外 IP 的。后面会支持代理的 feature ，不管部署在国内还是国外都可以用到。目前核心组件 https://github.com/foamzou/media-get 已经支持该 feature
2.  `youtube的播放按钮是灰色无法点击` ，这是因为 media-get 对 YouTube 的支持不是很完善，计划后面用成熟的组件 youtube-dl 之类的作为 YouTube 的支持组件（this plan may delay : (
