### ISSUE TITLE
b站有一个上传失败

### ISSUE THREAD

**Issue by usc** [foamzou/melody#9]
b站有一个上传失败，同up主有成功上传
https://www.bilibili.com/video/BV1BY4y1i777

附部分日志
ℹ -------
ℹ searchSong with {"0":{"songName":"【萨克斯】转音注入灵魂～《月牙湾》F.I.R. \"是谁的心啊，孤单地留下\"","artist":"Leon_Music","album":"Bilibili"}}
ℹ cmdStr: /melody/backend/src/service/media_fetcher/../../../bin/media-get --searchSongName "【萨克斯】转音注入灵魂～《月牙湾》F.I.R. "是谁的心啊，孤单地留下"" --searchArtist "Leon_Music" --searchAlbum "Bilibili" --searchType="song" -m --infoFormat=json -l silence
ℹ -------
ℹ 0
ℹ -------
ℹ songName not matched, continue. 【萨克斯】转音注入灵魂～《月牙湾》F.I.R. &quot;是谁的心啊，孤单地留下&quot; vs 【萨克斯】转音注入灵魂～《月牙湾》F.I.R. "是谁的心啊，孤单地留下"
ℹ songName not matched, continue. 月牙湾 (Live) vs 【萨克斯】转音注入灵魂～《月牙湾》F.I.R. "是谁的心啊，孤单地留下"

**Comment by foamzou** [comment]
Will fix the similar bug sunday.
