### ISSUE TITLE
[BUG]目前这项目还能用吗？ 我点了咪咕音乐 酷我音乐 都不能播放 只有b站还能用

### ISSUE THREAD

**Issue by learning-go123** [foamzou/melody#92]
## 请至少提供以下信息，帮助排查问题
1. 后端日志
`getMetaWithUrl from https://music.migu.cn/v3/music/song/6005751LC6X
/app/backend/src/service/media_fetcher/../../../bin/media-get [
  '-u',
  '"https://music.migu.cn/v3/music/song/6005751LC6X"',
  '-m',
  '--infoFormat=json'
]
ℹ -------
ℹ 0
ℹ -------`
3. F12 前端网络请求报文
4. F12 console 信息

**Comment by foamzou** [comment]
下版本 fix 咪咕
https://github.com/foamzou/melody/issues/82
