### ISSUE TITLE
[BUG]咪咕，酷我无法播放。哔哩哔哩灰色的无法点击。

### ISSUE THREAD

**Issue by lpx2223** [foamzou/melody#94]
我搜的是半壶纱。可以播放的歌曲倒是可以上传，但是都是最低音质的。
咪咕，酷我无法播放。哔哩哔哩灰色的无法点击。
是否可以添加一个更换歌源js的功能？（比如近期落雪后台换源搜索下载的那种？）

**Comment by ZACKLZ** [comment]
我看已经一年没更新了，是不是不再维护了···

**Comment by foamzou** [comment]
> 我看已经一年没更新了，是不是不再维护了···

还在。随缘更新，不好立 flag ，可能今年 Q1 更新一版
@ZACKLZ

**Comment by foamzou** [comment]
多个音乐平台的搜索/播放问题已经 fix。详见 https://github.com/foamzou/melody/releases/tag/v1.0.2
docker 同学可以执行以下命令更新版本
```
docker pull docker.io/foamzou/melody:latest
docker kill <CONTAINER ID>
docker run -d -p 5566:5566  -v ~/melody-profile:/app/backend/.profile foamzou/melody:latest
```

源码同学 git pull 最新代码后
```
npm run update && npm run app
```

回复下本帖的问题：
> 哔哩哔哩灰色的无法点击
b 站是视频网站，无法直接播放音频。你可以先查看原网页，如果音频是你想要的，直接点击上传就可以了 @lpx2223 

cc @ZACKLZ @a447948814 @x2287711259 @mufengyouyang @guxuanjun
